((css_hex_color) @colors.css)
((css_named_color) @colors.css)
((css_keyword_transparent) @colors.css)
((css_function_rgb) @colors.css)
((css_function_rgba) @colors.css)
((css_function_hsl) @colors.css)
((css_function_hsla) @colors.css)
((css_function_hwb) @colors.css)
((css_function_lab) @colors.css)
((css_function_oklab) @colors.css)
((css_function_lch) @colors.css)
((css_function_oklch) @colors.css)
((css_function_color_rgb) @colors.css)
((css_function_color_xyz) @colors.css)

((u32_argb) @colors.u32_argb)
